# Generated by Django 4.2.5 on 2023-09-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneDiseaseAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_symbol', models.CharField(max_length=255, verbose_name='geneSymbol_text')),
                ('disease_name', models.CharField(max_length=255, verbose_name='diseaseName')),
                ('score', models.FloatField()),
            ],
        ),
    ]
